### PR TITLE
Add support for hupper -m

### PR DESCRIPTION
**Pull request by dstufft**

### CODE REVIEW

**Comment by mmerickel** [comment]
This looks great. I tried to run the test suite directly but it doesn't seem too happy about it.

```
❯ env/bin/hupper -m tests.myapp.cli.main
Starting monitor for PID 46170.
Process Process-1:
Traceback (most recent call last):
  File "/Users/michael/.pyenv/versions/3.5.2/lib/python3.5/runpy.py", line 119, in _get_module_details
    spec = importlib.util.find_spec(mod_name)
  File "/Users/michael/.pyenv/versions/3.5.2/lib/python3.5/importlib/util.py", line 88, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ImportError: No module named 'tests'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/michael/.pyenv/versions/3.5.2/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/Users/michael/.pyenv/versions/3.5.2/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/michael/work/oss/hupper/src/hupper/worker.py", line 241, in worker_main
    func(*spec_args, **spec_kwargs)
  File "/Users/michael/.pyenv/versions/3.5.2/lib/python3.5/runpy.py", line 192, in run_module
    mod_name, mod_spec, code = _get_module_details(mod_name)
  File "/Users/michael/.pyenv/versions/3.5.2/lib/python3.5/runpy.py", line 125, in _get_module_details
    raise error(msg.format(mod_name, type(ex).__name__, ex)) from ex
ImportError: Error while finding spec for 'tests.myapp.cli.main' (ImportError: No module named 'tests')
Killing server with PID 46170.
Starting monitor for PID 46171.
```

To compare, I can run `env/bin/python -m tests.myapp --reload` successfully, so even though the "tests" module is on my path it doesn't appear runpy is finding it.

**Comment by dstufft** [comment]
@mmerickel Well it'd be ``env/bin/hupper -m tests.mapp``, IOW it is supposed to mimc ``python -m``.

That being said, the reason this isn't working is a difference between invoking python itself, and invoking a script. When invoking python itself ``''`` is added to the front of ``sys.path``, but when invoking a script, the directory that the script is contained in is added to the front of ``sys.path`` instead. I see a few options:

1. Do nothing, projects will just need to ensure their things are *actually* on ``sys.path``.
2. Just add ``''`` to the front of ``sys.path`` when being invoked as ``hupper -m``.
3. Attempt to replace the directory ``hupper`` is in on ``sys.path`` with ``''``.

Out of all of them, 3 will match the behavior of ``python -m`` best, but I fear it will be somewhat brittle and error-prone. I feel like 2 is the right answer here.

**Comment by mmerickel** [comment]
I'm wondering if there's any reason to have the `-m` flag. We could add a `__main__.py` and have `python -m hupper <module>` and `hupper <module>` without it. It's also a required argument so hiding behind a flag may not be best.

**Comment by dstufft** [comment]
@mmerickel I wondered the same thing actually! The main reason i kept it was symmetry with ``python -m`` and incase hupper ever wanted to get _other_ modes.

**Comment by mmerickel** [comment]
For sure, I appreciate the concern. It's fine to leave it the way it is for now. I could see another mode where hupper can run a script instead of an importable module and so `-m` might be best. At that point `-m` would become just a flag.

For example, `python -m hupper myscript.py` where hupper could come up with a way to start the reloader and then the worker would exec the script.

It was an annoyance when developing hupper that the importable string was required, but I couldn't come up with a better way at the time. I hope it can get removed by someone smarter than me.

**Comment by mmerickel** [comment]
So I'd say also option 2 is the best here. It seems the cwd should be on the path to mirror `python -m`.

**Comment by dstufft** [comment]
Ok Option 2 is implemented now. I had to slightly tweak the test app because it correctly detected that it was being ran under hupper already, but it didn't have a reference to the reloader since it was started with ``hupper -m`` instead of adding a ``--reload`` flag to the command itself. Switching it to use ``get_reloader()`` instead and verified that touching ``foo.ini`` still reloads it.

**Comment by mmerickel** [comment]
Thanks!

**Pull request merged**
